// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szgwfszqgfftmerjyylq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6Z3dmc3pxZ2ZmdG1lcmp5eWxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MjE0MDAsImV4cCI6MjA2NDA5NzQwMH0.Wm5ZG9XYuMA7JVEdYqkBATGWMtekyXbkDnL3HNe-Tmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);